# Generated by Django 6.0.3 on 2026-04-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_admissionapplication_contactmessage_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='EduCare International School', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='tagline',
            field=models.CharField(blank=True, default='Nurturing Young Minds for Excellence', max_length=300),
        ),
    ]
