@extends('layouts.app')
@section('title','Document History')
@section('subtitle','Audit trail of all generated documents with QR verification')

@section('content')
<div class="space-y-5">

<div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
    <form method="GET" class="grid grid-cols-1 sm:grid-cols-3 gap-4 items-end">
        <div>
            <label class="block text-xs font-bold uppercase tracking-wider text-slate-600 mb-1.5">Document Type</label>
            <select name="type" class="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-slate-400">
                <option value="">All Types</option>
                @foreach(['report_card','transcript','fee_statement','attendance_summary','class_performance'] as $t)
                <option value="{{ $t }}" {{ request('type')==$t?'selected':'' }}>{{ ucwords(str_replace('_',' ',$t)) }}</option>
                @endforeach
            </select>
        </div>
        <div>
            <label class="block text-xs font-bold uppercase tracking-wider text-slate-600 mb-1.5">Student</label>
            <select name="student_id" class="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-slate-400">
                <option value="">All Students</option>
                @foreach($students as $s)
                <option value="{{ $s->id }}" {{ request('student_id')==$s->id?'selected':'' }}>{{ $s->student_id }} — {{ $s->user->full_name }}</option>
                @endforeach
            </select>
        </div>
        <button type="submit" class="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-700 hover:bg-slate-600 text-white text-sm font-bold py-2.5 px-5 shadow transition-all active:scale-95">
            <i class="fas fa-filter text-xs"></i> Filter
        </button>
    </form>
</div>

<div class="rounded-2xl border border-slate-200 bg-white shadow-sm overflow-hidden">
    <div class="px-5 py-4 border-b border-slate-100 bg-slate-50">
        <h3 class="text-sm font-extrabold text-slate-800">Generated Documents</h3>
    </div>
    <div class="overflow-x-auto">
        <table class="w-full text-sm">
            <thead>
                <tr class="text-[11px] font-bold uppercase tracking-wider text-slate-400 border-b border-slate-100">
                    <th class="px-5 py-3 text-left">Document</th>
                    <th class="px-4 py-3 text-left">Student</th>
                    <th class="px-4 py-3 text-left">Generated By</th>
                    <th class="px-4 py-3 text-left">Date</th>
                    <th class="px-4 py-3 text-center">Status</th>
                    <th class="px-4 py-3 text-center">Verify</th>
                </tr>
            </thead>
            <tbody class="divide-y divide-slate-50">
                @forelse($docs as $doc)
                <tr class="hover:bg-slate-50 transition-colors">
                    <td class="px-5 py-3">
                        <p class="font-bold text-slate-800 text-sm">{{ $doc->title }}</p>
                        <p class="text-[11px] text-slate-400">{{ ucwords(str_replace('_',' ',$doc->document_type)) }}</p>
                    </td>
                    <td class="px-4 py-3 text-slate-600 font-medium text-xs">{{ $doc->student?->user?->full_name ?? '—' }}</td>
                    <td class="px-4 py-3 text-slate-600 text-xs">{{ $doc->generated_by_name }}</td>
                    <td class="px-4 py-3 text-slate-400 text-xs">{{ $doc->created_at->format('M d, Y H:i') }}</td>
                    <td class="px-4 py-3 text-center">
                        <span class="rounded-full px-2.5 py-0.5 text-[11px] font-extrabold {{ $doc->status==='valid'?'bg-emerald-100 text-emerald-700':'bg-red-100 text-red-700' }}">
                            {{ ucfirst($doc->status) }}
                        </span>
                    </td>
                    <td class="px-4 py-3 text-center">
                        <a href="{{ $doc->verify_url }}" target="_blank"
                           class="inline-flex items-center gap-1 rounded-lg bg-indigo-50 hover:bg-indigo-100 text-indigo-700 text-[11px] font-bold px-2.5 py-1.5 transition-colors">
                            <i class="fas fa-qrcode text-[10px]"></i> Verify
                        </a>
                    </td>
                </tr>
                @empty
                <tr><td colspan="6" class="text-center py-10 text-sm text-slate-400">No documents generated yet.</td></tr>
                @endforelse
            </tbody>
        </table>
    </div>
    @if($docs->hasPages())
    <div class="px-5 py-4 border-t border-slate-100">{{ $docs->links() }}</div>
    @endif
</div>

</div>
@endsection
