<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        // Drop the CHECK constraint that restricts role to the original four values.
        // The constraint name was auto-generated by Laravel's enum migration.
        // This allows any role string (secretary, etc.) to be stored.
        DB::statement("
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.table_constraints
                    WHERE table_name = 'staff_portal_users'
                    AND constraint_name = 'staff_portal_users_role_check'
                ) THEN
                    ALTER TABLE staff_portal_users DROP CONSTRAINT staff_portal_users_role_check;
                END IF;
            END
            $$;
        ");

        // Also ensure column is varchar in case it's still an enum type
        DB::statement("ALTER TABLE staff_portal_users ALTER COLUMN role TYPE VARCHAR(50) USING role::text::VARCHAR(50)");
    }

    public function down(): void
    {
        // Re-add the original check constraint if rolling back
        DB::statement("
            ALTER TABLE staff_portal_users
            ADD CONSTRAINT staff_portal_users_role_check
            CHECK (role::text = ANY (ARRAY['accountant'::text, 'headmaster'::text, 'headteacher'::text, 'deputy'::text]))
        ");
    }
};
